name: .NET Build & Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop, staging ]
    paths-ignore: [ '.github' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --filter FullyQualifiedName\!~Integration --no-build --verbosity normal
